// projects/flaux-co/src/app/shared/footer/footer.component.ts
import { Component, inject } from '@angular/core';
import { MatBottomSheet, MatBottomSheetModule } from '@angular/material/bottom-sheet';
import { RouterModule } from '@angular/router';
import { TermsOfServiceComponent } from '../legal-policies/terms-of-service.component';
import { PrivacyPolicyComponent } from '../legal-policies/privacy-policy.component';
import { CookiePolicyComponent } from '../legal-policies/cookie-policy.component';

@Component({
	selector: 'flaux-footer',
	templateUrl: './footer.component.html',
	styleUrls: ['./footer.component.scss'],
	standalone: true,
	imports: [RouterModule, MatBottomSheetModule]
})
export class FooterComponent {
	private bottomSheet = inject(MatBottomSheet);

	openPrivacyPolicy(): void {
		this.bottomSheet.open(PrivacyPolicyComponent, {
			panelClass: 'legal-bottom-sheet',
			backdropClass: 'legal-bottom-sheet-backdrop'
		});
	}

	openTermsOfService(): void {
		this.bottomSheet.open(TermsOfServiceComponent, {
			panelClass: 'legal-bottom-sheet',
			backdropClass: 'legal-bottom-sheet-backdrop'
		});
	}

	openCookiePolicy(): void {
		this.bottomSheet.open(CookiePolicyComponent, {
			panelClass: 'legal-bottom-sheet',
			backdropClass: 'legal-bottom-sheet-backdrop'
		});
	}

	currentYear: number = new Date().getFullYear();
}

<footer>
	<div class="footer-content">
		<div class="footer-columns">
			<div class="footer-logo">
				<a routerLink="/">
					<img src="../../assets/logo/svg/flaux.svg"
						  alt="flaux-co logo"
						  class="footer-logo-img">
				</a>
			</div>
			<div class="footer-column">
				<h3>Company</h3>
				<a routerLink="/">Home</a>
				<a routerLink="/">About</a>
				<a routerLink="/solutions/ai">AI Solutions</a>
				<a routerLink="/solutions/agency">Digital Solutions</a>
			</div>

			<div class="footer-column">
				<h3>Resources</h3>
				<a (click)="openPrivacyPolicy()">Privacy Policy</a>
				<a (click)="openTermsOfService()">Terms of Service</a>
				<a (click)="openCookiePolicy()">Cookie Policy</a>
				<a routerLink="/">Sitemap</a>
			</div>

			<div class="footer-column">
				<h3>Contact FLAUX</h3>
				<a routerLink="/contact">Contact</a>
			</div>
		</div>
	</div>

	<p>&copy; {{ currentYear }} FLAUX &mdash; All rights reserved.</p>

</footer>

// projects/flaux-co-react-WIP/src/components/footer/Footer.tsx
import { Link } from 'react-router-dom'
import './Footer.scss'

export const Footer: React.FC = () => {
  return (
    <footer>
      <div className="footer-content">
        <img src="/logo/SVG/Logo-Set-4.svg" alt="flaux-co logo" className="footer-logo" />
        <div className="footer-links">
          <Link to="/">Home</Link>
          <Link to="/about">About</Link>
          <Link to="/solutions">Solutions</Link>
          <Link to="/pricing">Pricing</Link>
          <Link to="/contact">Contact</Link>
        </div>
      </div>
      <p>&copy; 2025 FLAUX &mdash; All rights reserved.</p>
    </footer>
  )
}
