// projects/flaux-co/src/components/dropdown-menu/dropdown-menu.component.ts
import { Component, OnInit, OnDestroy, inject } from '@angular/core';
import { RouterModule } from '@angular/router';
import { UxService } from '../../services/ux.service';

@Component({
  selector: 'flaux-dropdown-menu',
  standalone: true,
  imports: [RouterModule],
  templateUrl: './dropdown-menu.component.html',
  styleUrls: ['./dropdown-menu.component.scss'],
})
export class DropdownMenuComponent implements OnInit, OnDestroy {
  private uxService = inject(UxService);
  isMenuOpen = this.uxService.isDropdownOpen;

  ngOnInit() {
    // Close dropdown when clicking outside
    document.addEventListener('click', (event) => {
      if (!(event.target as Element).closest('.dropdown-menu') &&
          !(event.target as Element).closest('.dropdown-trigger')) {
        this.uxService.closeDropdown();
      }
    });
  }

  ngOnDestroy() {
    // Clean up is handled automatically by the service
  }
}

<div class="dropdown-menu" [class.open]="isMenuOpen()">
  <a routerLink="/blog" routerLinkActive="active">Blog / Insights</a>
  <a routerLink="/about" routerLinkActive="active">About</a>
  <a routerLink="/contact" routerLinkActive="active">Contact</a>
  <a routerLink="/login" routerLinkActive="active">Login</a>
  <a routerLink="/signup" routerLinkActive="active">Signup</a>
  <a routerLink="/reset-password" routerLinkActive="active">Reset Password</a>
  <a routerLink="/checkout" routerLinkActive="active">Checkout</a>
  <a routerLink="/dashboard" routerLinkActive="active">Dashboard</a>
</div>

// projects/flaux-co-react-WIP/src/components/dropdown-menu/DropdownMenu.tsx
import { useEffect } from 'react'
import { Link, useLocation } from 'react-router-dom'
import { useUxService } from '@services/ux.service'
import './DropdownMenu.scss'

export const DropdownMenu: React.FC = () => {
  const location = useLocation()
  const { isDropdownOpen, closeDropdown } = useUxService()

  const isActiveRoute = (path: string) => {
    return location.pathname === path ? 'active' : ''
  }

  useEffect(() => {
    const handleClickOutside = (event: MouseEvent) => {
      const target = event.target as Element
      if (!target.closest('.dropdown-menu') && !target.closest('.dropdown-trigger')) {
        closeDropdown()
      }
    }

    document.addEventListener('click', handleClickOutside)
    return () => {
      document.removeEventListener('click', handleClickOutside)
    }
  }, [closeDropdown])

  return (
    <div className={`dropdown-menu ${isDropdownOpen ? 'open' : ''}`}>
      <Link 
        to="/blog" 
        className={isActiveRoute('/blog')}
      >
        Blog / Insights
      </Link>
      <Link 
        to="/about" 
        className={isActiveRoute('/about')}
      >
        About
      </Link>
      <Link 
        to="/contact" 
        className={isActiveRoute('/contact')}
      >
        Contact
      </Link>
      <Link 
        to="/login" 
        className={isActiveRoute('/login')}
      >
        Login
      </Link>
      <Link 
        to="/signup" 
        className={isActiveRoute('/signup')}
      >
        Signup
      </Link>
      <Link 
        to="/reset-password" 
        className={isActiveRoute('/reset-password')}
      >
        Reset Password
      </Link>
      <Link 
        to="/checkout" 
        className={isActiveRoute('/checkout')}
      >
        Checkout
      </Link>
      <Link 
        to="/dashboard" 
        className={isActiveRoute('/dashboard')}
      >
        Dashboard
      </Link>
    </div>
  )
}
