// projects/flaux-co-react-WIP/src/components/footer/Footer.tsx
import { Link } from 'react-router-dom'
import './Footer.scss'

export const Footer: React.FC = () => {
  return (
    <footer>
      <div className="footer-content">
        <img src="/logo/SVG/Logo-Set-4.svg" alt="flaux-co logo" className="footer-logo" />
        <div className="footer-links">
          <Link to="/">Home</Link>
          <Link to="/about">About</Link>
          <Link to="/solutions">Solutions</Link>
          <Link to="/pricing">Pricing</Link>
          <Link to="/contact">Contact</Link>
        </div>
      </div>
      <p>&copy; 2025 FLAUX &mdash; All rights reserved.</p>
    </footer>
  )
}

// projects/flaux-co/src/components/footer/footer.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'flaux-footer',
  templateUrl: './footer.component.html',
  styleUrls: ['./footer.component.scss'],
  standalone: true,
})
export class FooterComponent {}

<footer>
	<div class="footer-content">
		<div class="footer-columns">
			<div class="footer-logo">
				<a routerLink="/">
					<img src="../../assets/logo/svg/flaux.svg"
						  alt="flaux-co logo"
						  class="footer-logo-img">
				</a>
			</div>
			<div class="footer-column">
				<h3>Company</h3>
				<a routerLink="/">Home</a>
				<a routerLink="/">About</a>
				<a routerLink="/solutions/ai">AI Solutions</a>
				<a routerLink="/solutions/agency">Digital Solutions</a>
			</div>

			<div class="footer-column">
				<h3>Resources</h3>
				<a routerLink="/">Privacy Policy</a>
				<a routerLink="/">Terms of Service</a>
				<a routerLink="/">Cookie Policy</a>
				<a routerLink="/">Sitemap</a>
			</div>

			<div class="footer-column">
				<h3>Contact FLAUX</h3>
				<a routerLink="/contact">Contact</a>
			</div>
		</div>
	</div>

	<p>&copy; 2025 FLAUX &mdash; All rights reserved.</p>

</footer>
