// projects/flaux-co/src/components/navbar/navbar.component.ts
import { Component, Input } from '@angular/core';
import { RouterModule } from '@angular/router';
import { UxService } from '../../services/ux.service';
import { RippleDirective } from '../../app/directives/ripple.directive';

@Component({
  selector: 'flaux-navbar',
  standalone: true,
  imports: [RouterModule, RippleDirective],
  templateUrl: './navbar.component.html',
  styleUrls: ['./navbar.component.scss'],
})
export class NavbarComponent {
  @Input() logo: string = 'assets/logo/SVG/Logo-Set-4.svg';

  constructor(private uxService: UxService) {}

  toggleDropdown() {
    this.uxService.toggleDropdown();
  }
}

<nav class="navbar">
  <div class="navbar-left">
    <a routerLink="/" class="logo-link">
      <div class="text-container-navbar">
        <img [src]="logo" alt="FLAUX Logo" class="logo-navbar" />
        <span class="fl-text">FL</span>
        <span class="a-with-macron">&nbsp;&nbsp;</span>
        <span class="ux-text">AUX</span>
      </div>
    </a>
  </div>
  <div class="navbar-center">
    <a routerLink="/solutions" routerLinkActive="active" flauxRipple>Solutions</a>
    <a routerLink="/demo" routerLinkActive="active">Demo</a>
    <a routerLink="/pricing" routerLinkActive="active">Pricing</a>
  </div>
  <div class="navbar-right">
    <button class="dropdown-trigger" (click)="toggleDropdown()" flauxRipple>
      <span></span><span></span><span></span>
    </button>
  </div>
</nav>

// projects/flaux-co-react-WIP/src/components/navbar/Navbar.tsx
import { Link, useLocation } from 'react-router-dom'
import { useUxService } from '@services/ux.service'
import './Navbar.scss'

interface NavbarProps {
  logo?: string
}

export const Navbar: React.FC<NavbarProps> = ({ 
  logo = '/logo/SVG/Logo-Set-4.svg' 
}) => {
  const location = useLocation()
  const { toggleDropdown } = useUxService()

  const isActiveRoute = (path: string) => {
    return location.pathname === path ? 'active' : ''
  }

  return (
    <nav className="navbar">
      <div className="navbar-left">
        <Link to="/" className="logo-link">
          <div className="text-logo-wrapper">
            <img src={logo} alt="FLAUX Logo" className="logo-navbar" />
            <span className="fl-text">FL</span>
            <span className="a-with-macron">&nbsp;&nbsp;</span>
            <span className="ux-text">AUX</span>
          </div>
        </Link>
      </div>
      <div className="navbar-center">
        <Link 
          to="/solutions" 
          className={isActiveRoute('/solutions')}
        >
          SOLUTIONS
        </Link>
        <Link 
          to="/demo" 
          className={isActiveRoute('/demo')}
        >
          DEMO
        </Link>
        <Link 
          to="/pricing" 
          className={isActiveRoute('/pricing')}
        >
          PRICING
        </Link>
      </div>
      <div className="navbar-right">
        <button className="dropdown-trigger" onClick={toggleDropdown}>
          <span></span>
          <span></span>
          <span></span>
        </button>
      </div>
    </nav>
  )
}
